stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Environment variables shared between scripts for all ORNL CI stages
.ornl_environment_template: &ornl_environment_variables
  variables:
    SCHEDULER_PARAMETERS: "-P CSC359 -nnodes 1 -W 30"
    WORKDIR: /gpfs/wolf/proj-shared/csc359/ci/${CI_PIPELINE_ID}
    
.ornl_test_script_template: &ornl_test_script_definition
  script:
    - |
      set -xv
      cd "$WORKDIR"
      MY_CLUSTER="ascent" ./BUILD.sh --test-only
      res=$?
      exit $res
  after_script:
    - |
      cd "$WORKDIR/.."
      rm -rf "$WORKDIR"

.ornl_script_template: &ornl_script_definition
  script:
    - |
      # Don't clean up this working directory - we need some of these files for
      # testing
      set -xv
      mkdir -p "$WORKDIR"
      cp -R ./* "$WORKDIR"
      cd "$WORKDIR"
      MY_CLUSTER="ascent" ./BUILD.sh --build-only || exit 1

# For Ascent CI
build_on_login_node:
  stage: build
  tags:
    - nobatch
  rules:
    - if: '$CI_PROJECT_PATH == "ecpcitest/exasgd/hiop"'
  <<: *ornl_script_definition
  <<: *ornl_environment_variables

test_on_compute_node:
  stage: test
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build_on_login_node
  tags:
    - batch
  rules:
    - if: '$CI_PROJECT_PATH == "ecpcitest/exasgd/hiop"'
  <<: *ornl_test_script_definition
  <<: *ornl_environment_variables
# ---
