name: Spack Builds

on: [push]

jobs:
  hiop_spack_builds:
    runs-on: ubuntu-22.04
    container: spack/ubuntu-jammy:latest
    strategy:
      matrix:
        spack_spec:
          - hiop@develop+mpi~raja~shared~kron~sparse ^openmpi ^libevent~openssl
          - hiop@develop~mpi~raja~shared~kron~sparse ^libevent~openssl
          - hiop@develop~mpi+raja~shared~kron~sparse ^libevent~openssl

            # We will need coinhsl for this, but what are the rules for using
            # a coinhsl tarball?
            # - hiop@develop~mpi~raja~shared~kron+sparse

    name: Build HiOp with Spack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Environment
        env:
          SPACK_SPEC: ${{ matrix.spack_spec }}
        run: |
          ls && pwd
          . /opt/spack/share/spack/setup-env.sh
          spack debug report
          # Just use the public mirror to bootstrap concretizer
          # https://spack.io/spack-binary-packages
          spack mirror add spack_public_mirror https://binaries.spack.io/develop
          spack buildcache keys --install --trust
          # Need to create an environment to install hiop in the action's branch
          spack env create -d ./spack-env
          spack env activate ./spack-env
          spack add $SPACK_SPEC target=x86_64
          spack develop --path $(pwd) --no-clone hiop@develop
          spack external find --all --exclude python
          spack concretize --reuse
          git config --global --add safe.directory $(pwd)
          spack --stacktrace install --fail-fast

